### PR TITLE
fix comment in setup rake task

### PR DESCRIPTION
**Pull request by Dwin357**

### CODE REVIEW

**Comment by rfunduk** [comment]
:) thanks

**Comment by Dwin357** [comment]
TY for curating the resource.  I haven't mastered it yet by any means, but
this is really helpful as an example to try and adapt from.

I'm actually pretty green at this, would you mind if I asked a question
about configuring the api keys for production?

Thanks!
-dwin

**Comment by rfunduk** [comment]
Sure shoot me an email anytime ([contact info here](https://ryanfunduk.com/contact/)).

**Comment by Dwin357** [comment]
Thanks!!!

**Pull request merged**
